image: node:12.18.4
pipelines:
  branches:
    Staging:
      - step:
          name: deployment to staging server
          caches:
            - node
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $STAGING_USER
                SERVER: $STAGING_HOST
                MODE: "command"
                COMMAND: "cd /var/www/leiaqa/website-leiaqa-staging && git stash && git pull origin Staging && sudo n 20.9.0 && hash -r && npm i && npm run build && git stash clear && pm2 restart leiaqa-website-staging"

    main:
      - step:
          name: deployment to production server
          deployment: production
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $PROD_USER
                SERVER: $PROD_HOST
                MODE: "command"
                COMMAND: "cd /var/www/leiaqa-v2/website-leiaqa && git stash && git pull origin main && sudo n 20.9.0 && hash -r && npm i && npm run build && git stash clear && pm2 restart leiaqa-website"
